set_property SRC_FILE_INFO {cfile:D:/2025/Learning/FPGA_Projects/mini_module_hello_world/mini_module_hello_world.srcs/constrs_1/new/pin.xdc rfile:../../../mini_module_hello_world.srcs/constrs_1/new/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F14 [ get_ports CLK_N]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports CLK_N]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F15 [ get_ports CLK_P]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports CLK_P]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB19 [ get_ports PJTAG_TCK]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports PJTAG_TCK]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA20 [ get_ports PJTAG_TMS]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports PJTAG_TMS]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y20 [ get_ports PJTAG_TD_I]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports PJTAG_TD_I]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB20 [ get_ports PJTAG_TD_O]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports PJTAG_TD_O]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF10 [ get_ports LVDS_CLK_P]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports LVDS_CLK_P]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF9 [ get_ports LVDS_CLK_N]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports LVDS_CLK_N]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD19 [ get_ports CDCM_OD0]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports CDCM_OD0]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC18 [ get_ports CDCM_OD1]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports CDCM_OD1]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD18 [ get_ports CDCM_OD2]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports CDCM_OD2]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC19 [ get_ports CDCM_PR0]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports CDCM_PR0]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA19 [ get_ports CDCM_PR1]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports CDCM_PR1]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA18 [ get_ports CDCM_RST_N]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports CDCM_RST_N]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C8 [ get_ports Linear_Flash_address_out[26]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[26]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B6 [ get_ports Linear_Flash_address_out[25]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[25]]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K8 [ get_ports Linear_Flash_address_out[24]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[24]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M10 [ get_ports Linear_Flash_address_out[23]]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[23]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B7 [ get_ports Linear_Flash_address_out[22]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[22]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D9 [ get_ports Linear_Flash_address_out[21]]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[21]]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C6 [ get_ports Linear_Flash_address_out[20]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[20]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C9 [ get_ports Linear_Flash_address_out[19]]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[19]]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A7 [ get_ports Linear_Flash_address_out[18]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[18]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E10 [ get_ports Linear_Flash_address_out[17]]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[17]]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E8 [ get_ports Linear_Flash_address_out[16]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[16]]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D8 [ get_ports Linear_Flash_address_out[15]]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[15]]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C7 [ get_ports Linear_Flash_address_out[14]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[14]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A8 [ get_ports Linear_Flash_address_out[13]]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[13]]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E11 [ get_ports Linear_Flash_address_out[12]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[12]]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F9 [ get_ports Linear_Flash_address_out[11]]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[11]]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F10 [ get_ports Linear_Flash_address_out[10]]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[10]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D11 [ get_ports Linear_Flash_address_out[9]]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[9]]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B9 [ get_ports Linear_Flash_address_out[8]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[8]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G11 [ get_ports Linear_Flash_address_out[7]]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[7]]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A10 [ get_ports Linear_Flash_address_out[6]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[6]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F8 [ get_ports Linear_Flash_address_out[5]]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[5]]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F7 [ get_ports Linear_Flash_address_out[4]]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[4]]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D6 [ get_ports Linear_Flash_address_out[3]]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[3]]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D10 [ get_ports Linear_Flash_address_out[2]]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[2]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A9 [ get_ports Linear_Flash_address_out[1]]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_address_out[1]]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G7 [ get_ports Linear_Flash_adv_ldn]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_adv_ldn]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B10 [ get_ports Linear_Flash_ce_n[0]]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_ce_n[0]]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G9 [ get_ports Linear_Flash_data_io[15]]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[15]]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J8 [ get_ports Linear_Flash_data_io[14]]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[14]]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L7 [ get_ports Linear_Flash_data_io[13]]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[13]]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H7 [ get_ports Linear_Flash_data_io[12]]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[12]]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L8 [ get_ports Linear_Flash_data_io[11]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[11]]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L9 [ get_ports Linear_Flash_data_io[10]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[10]]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H11 [ get_ports Linear_Flash_data_io[9]]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[9]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G10 [ get_ports Linear_Flash_data_io[8]]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[8]]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K7 [ get_ports Linear_Flash_data_io[7]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[7]]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J10 [ get_ports Linear_Flash_data_io[6]]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[6]]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K10 [ get_ports Linear_Flash_data_io[5]]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[5]]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J11 [ get_ports Linear_Flash_data_io[4]]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[4]]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K12 [ get_ports Linear_Flash_data_io[3]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[3]]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L10 [ get_ports Linear_Flash_data_io[2]]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[2]]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H12 [ get_ports Linear_Flash_data_io[1]]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[1]]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L12 [ get_ports Linear_Flash_data_io[0]]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_data_io[0]]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H8 [ get_ports Linear_Flash_oe_n[0]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_oe_n[0]]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J9 [ get_ports Linear_Flash_we_n]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [ get_ports Linear_Flash_we_n]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD9 [ get_ports JX1_MGTREFCLK_N]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTREFCLK_N]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD10 [ get_ports JX1_MGTREFCLK_P]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTREFCLK_P]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF22 [ get_ports JX1_DIFF_CLKIN_N]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_CLKIN_N]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE22 [ get_ports JX1_DIFF_CLKIN_P]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_CLKIN_P]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH21 [ get_ports JX1_DIFF_RCLKIN_N]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_RCLKIN_N]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG21 [ get_ports JX1_DIFF_RCLKIN_P]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_RCLKIN_P]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ19 [ get_ports JX1_DIFF_IO_0_N]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_0_N]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH19 [ get_ports JX1_DIFF_IO_0_P]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_0_P]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK18 [ get_ports JX1_DIFF_IO_1_N]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_1_N]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK17 [ get_ports JX1_DIFF_IO_1_P]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_1_P]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG20 [ get_ports JX1_DIFF_IO_2_N]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_2_N]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF20 [ get_ports JX1_DIFF_IO_2_P]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_2_P]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK23 [ get_ports JX1_DIFF_IO_3_N]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_3_N]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK22 [ get_ports JX1_DIFF_IO_3_P]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_3_P]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK20 [ get_ports JX1_DIFF_IO_4_N]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_4_N]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ20 [ get_ports JX1_DIFF_IO_4_P]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_4_P]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ24 [ get_ports JX1_DIFF_IO_5_N]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_5_N]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ23 [ get_ports JX1_DIFF_IO_5_P]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_5_P]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK21 [ get_ports JX1_DIFF_IO_6_N]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_6_N]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ21 [ get_ports JX1_DIFF_IO_6_P]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_6_P]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH24 [ get_ports JX1_DIFF_IO_7_N]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_7_N]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH23 [ get_ports JX1_DIFF_IO_7_P]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_7_P]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE21 [ get_ports JX1_DIFF_IO_8_N]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_8_N]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD21 [ get_ports JX1_DIFF_IO_8_P]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_8_P]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK25 [ get_ports JX1_DIFF_IO_9_N]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_9_N]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ25 [ get_ports JX1_DIFF_IO_9_P]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_9_P]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE23 [ get_ports JX1_DIFF_IO_10_N]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_10_N]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD23 [ get_ports JX1_DIFF_IO_10_P]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_10_P]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD24 [ get_ports JX1_DIFF_IO_11_N]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_11_N]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC24 [ get_ports JX1_DIFF_IO_11_P]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_11_P]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF24 [ get_ports JX1_DIFF_IO_12_N]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_12_N]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF23 [ get_ports JX1_DIFF_IO_12_P]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_12_P]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG25 [ get_ports JX1_DIFF_IO_13_N]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_13_N]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG24 [ get_ports JX1_DIFF_IO_13_P]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_DIFF_IO_13_P]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH9 [ get_ports JX1_MGTRX0_N]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX0_N]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH10 [ get_ports JX1_MGTRX0_P]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX0_P]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ7 [ get_ports JX1_MGTRX1_N]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX1_N]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ8 [ get_ports JX1_MGTRX1_P]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX1_P]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG7 [ get_ports JX1_MGTRX2_N]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX2_N]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG8 [ get_ports JX1_MGTRX2_P]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX2_P]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE7 [ get_ports JX1_MGTRX3_N]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX3_N]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE8 [ get_ports JX1_MGTRX3_P]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTRX3_P]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK9 [ get_ports JX1_MGTTX0_N]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX0_N]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK10 [ get_ports JX1_MGTTX0_P]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX0_P]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK5 [ get_ports JX1_MGTTX1_N]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX1_N]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK6 [ get_ports JX1_MGTTX1_P]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX1_P]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ3 [ get_ports JX1_MGTTX2_N]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX2_N]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ4 [ get_ports JX1_MGTTX2_P]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX2_P]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK1 [ get_ports JX1_MGTTX3_N]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX3_N]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK2 [ get_ports JX1_MGTTX3_P]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_MGTTX3_P]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF14 [ get_ports JX1_SE_CLKIN]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports JX1_SE_CLKIN]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC14 [ get_ports JX1_SE_IO_32]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports JX1_SE_IO_32]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF17 [ get_ports JX1_SE_IO_0_N]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_0_N]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF18 [ get_ports JX1_SE_IO_0_P]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_0_P]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ18 [ get_ports JX1_SE_IO_2_N]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_2_N]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH18 [ get_ports JX1_SE_IO_2_P]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_2_P]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG16 [ get_ports JX1_SE_IO_4_N]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_4_N]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG17 [ get_ports JX1_SE_IO_4_P]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_4_P]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF12 [ get_ports JX1_SE_IO_6_N]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_6_N]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE12 [ get_ports JX1_SE_IO_6_P]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_6_P]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE15 [ get_ports JX1_SE_IO_8_N]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_8_N]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE16 [ get_ports JX1_SE_IO_8_P]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_8_P]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF13 [ get_ports JX1_SE_IO_10_N]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_10_N]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE13 [ get_ports JX1_SE_IO_10_P]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_10_P]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE17 [ get_ports JX1_SE_IO_12_N]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_12_N]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE18 [ get_ports JX1_SE_IO_12_P]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_12_P]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH12 [ get_ports dip_switches_8bits_tri_i[0]]		# DIP_SW1 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG12 [ get_ports dip_switches_8bits_tri_i[1]]		# DIP_SW0 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG15 [ get_ports dip_switches_8bits_tri_i[2]]		# DIP_SW3 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF15 [ get_ports dip_switches_8bits_tri_i[3]]		# DIP_SW2 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK16 [ get_ports dip_switches_8bits_tri_i[4]]		# DIP_SW5 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ16 [ get_ports dip_switches_8bits_tri_i[5]]		# DIP_SW4 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK12 [ get_ports dip_switches_8bits_tri_i[6]]		# DIP_SW7 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK13 [ get_ports dip_switches_8bits_tri_i[7]]		# DIP_SW6 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH13 [ get_ports led_5bits_tri_o[0]]		# LED1 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH14 [ get_ports led_5bits_tri_o[1]]		# LED0 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD15 [ get_ports led_5bits_tri_o[2]]		# LED3 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD16 [ get_ports led_5bits_tri_o[3]]		# LED2 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD14 [ get_ports led_5bits_tri_o[5]]		# LED4 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports led_5bits_tri_o[5]]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ13 [ get_ports JX1_SE_IO_30_N]		# UART_TX on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_30_N]
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AJ14 [ get_ports JX1_SE_IO_30_P]		# UART_RX on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX1_SE_IO_30_P]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N7 [ get_ports JX2_MGTREFCLK_N]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTREFCLK_N]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N8 [ get_ports JX2_MGTREFCLK_P]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTREFCLK_P]
set_property src_info {type:XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U27 [ get_ports JX2_DIFF_CLKIN_N]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_CLKIN_N]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U26 [ get_ports JX2_DIFF_CLKIN_P]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_CLKIN_P]
set_property src_info {type:XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R26 [ get_ports JX2_DIFF_RCLKIN_N]
set_property src_info {type:XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_RCLKIN_N]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R25 [ get_ports JX2_DIFF_RCLKIN_P]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_RCLKIN_P]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V29 [ get_ports JX2_DIFF_IO_0_N]
set_property src_info {type:XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_0_N]
set_property src_info {type:XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V28 [ get_ports JX2_DIFF_IO_0_P]
set_property src_info {type:XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_0_P]
set_property src_info {type:XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V26 [ get_ports JX2_DIFF_IO_1_N]
set_property src_info {type:XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_1_N]
set_property src_info {type:XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U25 [ get_ports JX2_DIFF_IO_1_P]
set_property src_info {type:XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_1_P]
set_property src_info {type:XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W30 [ get_ports JX2_DIFF_IO_2_N]
set_property src_info {type:XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_2_N]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W29 [ get_ports JX2_DIFF_IO_2_P]
set_property src_info {type:XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_2_P]
set_property src_info {type:XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R30 [ get_ports JX2_DIFF_IO_3_N]
set_property src_info {type:XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_3_N]
set_property src_info {type:XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P30 [ get_ports JX2_DIFF_IO_3_P]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_3_P]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U29 [ get_ports JX2_DIFF_IO_4_N]
set_property src_info {type:XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_4_N]
set_property src_info {type:XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T29 [ get_ports JX2_DIFF_IO_4_P]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_4_P]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W26 [ get_ports JX2_DIFF_IO_5_N]
set_property src_info {type:XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_5_N]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W25 [ get_ports JX2_DIFF_IO_5_P]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_5_P]
set_property src_info {type:XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U30 [ get_ports JX2_DIFF_IO_6_N]
set_property src_info {type:XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_6_N]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T30 [ get_ports JX2_DIFF_IO_6_P]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_6_P]
set_property src_info {type:XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T27 [ get_ports JX2_DIFF_IO_7_N]
set_property src_info {type:XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_7_N]
set_property src_info {type:XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R27 [ get_ports JX2_DIFF_IO_7_P]
set_property src_info {type:XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_7_P]
set_property src_info {type:XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N27 [ get_ports JX2_DIFF_IO_8_N]
set_property src_info {type:XDC file:1 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_8_N]
set_property src_info {type:XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N26 [ get_ports JX2_DIFF_IO_8_P]
set_property src_info {type:XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_8_P]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P26 [ get_ports JX2_DIFF_IO_9_N]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_9_N]
set_property src_info {type:XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P25 [ get_ports JX2_DIFF_IO_9_P]
set_property src_info {type:XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_9_P]
set_property src_info {type:XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P28 [ get_ports JX2_DIFF_IO_10_N]
set_property src_info {type:XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_10_N]
set_property src_info {type:XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N28 [ get_ports JX2_DIFF_IO_10_P]
set_property src_info {type:XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_10_P]
set_property src_info {type:XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T25 [ get_ports JX2_DIFF_IO_11_N]
set_property src_info {type:XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_11_N]
set_property src_info {type:XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T24 [ get_ports JX2_DIFF_IO_11_P]
set_property src_info {type:XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_11_P]
set_property src_info {type:XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P29 [ get_ports JX2_DIFF_IO_12_N]
set_property src_info {type:XDC file:1 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_12_N]
set_property src_info {type:XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N29 [ get_ports JX2_DIFF_IO_12_P]
set_property src_info {type:XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_12_P]
set_property src_info {type:XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W28 [ get_ports JX2_DIFF_IO_13_N]
set_property src_info {type:XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_13_N]
set_property src_info {type:XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V27 [ get_ports JX2_DIFF_IO_13_P]
set_property src_info {type:XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_DIFF_IO_13_P]
set_property src_info {type:XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U3 [ get_ports JX2_MGTRX0_N]
set_property src_info {type:XDC file:1 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX0_N]
set_property src_info {type:XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U4 [ get_ports JX2_MGTRX0_P]
set_property src_info {type:XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX0_P]
set_property src_info {type:XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V5 [ get_ports JX2_MGTRX1_N]
set_property src_info {type:XDC file:1 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX1_N]
set_property src_info {type:XDC file:1 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V6 [ get_ports JX2_MGTRX1_P]
set_property src_info {type:XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX1_P]
set_property src_info {type:XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P5 [ get_ports JX2_MGTRX2_N]
set_property src_info {type:XDC file:1 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX2_N]
set_property src_info {type:XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P6 [ get_ports JX2_MGTRX2_P]
set_property src_info {type:XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX2_P]
set_property src_info {type:XDC file:1 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T5 [ get_ports JX2_MGTRX3_N]
set_property src_info {type:XDC file:1 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX3_N]
set_property src_info {type:XDC file:1 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T6 [ get_ports JX2_MGTRX3_P]
set_property src_info {type:XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTRX3_P]
set_property src_info {type:XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R3 [ get_ports JX2_MGTTX0_N]
set_property src_info {type:XDC file:1 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX0_N]
set_property src_info {type:XDC file:1 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R4 [ get_ports JX2_MGTTX0_P]
set_property src_info {type:XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX0_P]
set_property src_info {type:XDC file:1 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T1 [ get_ports JX2_MGTTX1_N]
set_property src_info {type:XDC file:1 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX1_N]
set_property src_info {type:XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T2 [ get_ports JX2_MGTTX1_P]
set_property src_info {type:XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX1_P]
set_property src_info {type:XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N3 [ get_ports JX2_MGTTX2_N]
set_property src_info {type:XDC file:1 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX2_N]
set_property src_info {type:XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N4 [ get_ports JX2_MGTTX2_P]
set_property src_info {type:XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX2_P]
set_property src_info {type:XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P1 [ get_ports JX2_MGTTX3_N]
set_property src_info {type:XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX3_N]
set_property src_info {type:XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P2 [ get_ports JX2_MGTTX3_P]
set_property src_info {type:XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_MGTTX3_P]
set_property src_info {type:XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC18 [ get_ports JX2_SE_CLKIN]
set_property src_info {type:XDC file:1 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports JX2_SE_CLKIN]
set_property src_info {type:XDC file:1 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AH28 [ get_ports JX2_SE_IO_32]			# SD_CLK on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [ get_ports JX2_SE_IO_32]
set_property src_info {type:XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA30 [ get_ports JX2_SE_IO_0_N]		# PB1 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_0_N]
set_property src_info {type:XDC file:1 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y30 [ get_ports JX2_SE_IO_0_P]			# PB0 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_0_P]
set_property src_info {type:XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA29 [ get_ports JX2_SE_IO_2_N]		# PB3 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_2_N]
set_property src_info {type:XDC file:1 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y28 [ get_ports JX2_SE_IO_2_P]			# PB2 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_2_P]
set_property src_info {type:XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG27 [ get_ports JX2_SE_IO_4_N]
set_property src_info {type:XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_4_N]
set_property src_info {type:XDC file:1 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG26 [ get_ports JX2_SE_IO_4_P]
set_property src_info {type:XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_4_P]
set_property src_info {type:XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG29 [ get_ports JX2_SE_IO_6_N]
set_property src_info {type:XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_6_N]
set_property src_info {type:XDC file:1 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF29 [ get_ports JX2_SE_IO_6_P]
set_property src_info {type:XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_6_P]
set_property src_info {type:XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y27 [ get_ports JX2_SE_IO_8_N]
set_property src_info {type:XDC file:1 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_8_N]
set_property src_info {type:XDC file:1 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y26 [ get_ports JX2_SE_IO_8_P]
set_property src_info {type:XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_8_P]
set_property src_info {type:XDC file:1 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF25 [ get_ports JX2_SE_IO_10_N]
set_property src_info {type:XDC file:1 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_10_N]
set_property src_info {type:XDC file:1 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE25 [ get_ports JX2_SE_IO_10_P]
set_property src_info {type:XDC file:1 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_10_P]
set_property src_info {type:XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA28 [ get_ports JX2_SE_IO_12_N]
set_property src_info {type:XDC file:1 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_12_N]
set_property src_info {type:XDC file:1 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA27 [ get_ports JX2_SE_IO_12_P]
set_property src_info {type:XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_12_P]
set_property src_info {type:XDC file:1 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD26 [ get_ports JX2_SE_IO_14_N]
set_property src_info {type:XDC file:1 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_14_N]
set_property src_info {type:XDC file:1 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC26 [ get_ports JX2_SE_IO_14_P]
set_property src_info {type:XDC file:1 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_14_P]
set_property src_info {type:XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE30 [ get_ports JX2_SE_IO_16_N]
set_property src_info {type:XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_16_N]
set_property src_info {type:XDC file:1 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD30 [ get_ports JX2_SE_IO_16_P]
set_property src_info {type:XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_16_P]
set_property src_info {type:XDC file:1 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD29 [ get_ports JX2_SE_IO_18_N]
set_property src_info {type:XDC file:1 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_18_N]
set_property src_info {type:XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC29 [ get_ports JX2_SE_IO_18_P]
set_property src_info {type:XDC file:1 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_18_P]
set_property src_info {type:XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AG30 [ get_ports JX2_SE_IO_20_N]
set_property src_info {type:XDC file:1 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_20_N]
set_property src_info {type:XDC file:1 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF30 [ get_ports JX2_SE_IO_20_P]
set_property src_info {type:XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_20_P]
set_property src_info {type:XDC file:1 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF28 [ get_ports JX2_SE_IO_22_N]
set_property src_info {type:XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_22_N]
set_property src_info {type:XDC file:1 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE28 [ get_ports JX2_SE_IO_22_P]
set_property src_info {type:XDC file:1 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_22_P]
set_property src_info {type:XDC file:1 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC27 [ get_ports JX2_SE_IO_24_N]
set_property src_info {type:XDC file:1 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_24_N]
set_property src_info {type:XDC file:1 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB27 [ get_ports JX2_SE_IO_24_P]
set_property src_info {type:XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_24_P]
set_property src_info {type:XDC file:1 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF27 [ get_ports JX2_SE_IO_26_N]		# SD_D0 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_26_N]
set_property src_info {type:XDC file:1 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE27 [ get_ports JX2_SE_IO_26_P]
set_property src_info {type:XDC file:1 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_26_P]
set_property src_info {type:XDC file:1 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB30 [ get_ports JX2_SE_IO_28_N]		# SD_D2 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_28_N]
set_property src_info {type:XDC file:1 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB29 [ get_ports JX2_SE_IO_28_P]		# SD_D1 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_28_P]
set_property src_info {type:XDC file:1 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE26 [ get_ports JX2_SE_IO_30_N]		# SD_CMD on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_30_N]
set_property src_info {type:XDC file:1 line:724 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD25 [ get_ports JX2_SE_IO_30_P]		# SD_D3 on the MMP Baseboard 2, Use LVCMOS25
set_property src_info {type:XDC file:1 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [ get_ports JX2_SE_IO_30_P]
